In [2]:
import pandas as pd
final_df = pd.read_csv('results_until_21000.csv')
final_df.head(10)

,question,human_answers,chatgpt_answers,index,source,answer_gemini
0,"Why is every book I hear about a "" NY Times # ...","['Basically there are many categories of "" Bes...",['There are many different best seller lists t...,NaN,reddit_eli5,Imagine your classroom has a chart showing who...
1,"If salt is so bad for cars , why do we use it ...",['salt is good for not dying in car crashes an...,"[""Salt is used on roads to help melt ice and s...",NaN,reddit_eli5,Imagine it's winter and the roads are super ic...
2,Why do we still have SD TV channels when HD lo...,"[""The way it works is that old TV stations got...","[""There are a few reasons why we still have SD...",NaN,reddit_eli5,"Imagine you have two toy cars: one is a shiny,..."
3,Why has nobody assassinated Kim Jong - un He i...,"[""You ca n't just go around assassinating the ...",['It is generally not acceptable or ethical to...,NaN,reddit_eli5,Imagine Kim Jong-un is a really grumpy kid wit...
4,How was airplane technology able to advance so...,['Wanting to kill the shit out of Germans driv...,['After the Wright Brothers made the first pow...,NaN,reddit_eli5,"Imagine you built the very first LEGO castle, ..."
5,Why do humans have different colored eyes ? Wh...,['Melanin ! Many of the the first known humans...,['The color of your eyes is determined by the ...,NaN,reddit_eli5,Imagine your eyes are like little bowls. Insi...
6,Why I can not fabricate a religion that preven...,"[""Because you 're a minor and your parents get...",['The First Amendment to the United States Con...,NaN,reddit_eli5,Imagine you want to build a really cool LEGO c...
7,What has changed that we frequently now throw ...,"[""It 's three fold : * Stuff is cheaper to mas...",['There are a few different factors that can c...,NaN,reddit_eli5,"Imagine you have a toy car, and a wheel falls ..."
8,magic the gathering What is it . how popular i...,"['EDIT , Nov 21 : By popular demand , now incl...",['Magic: The Gathering is a collectible card g...,NaN,reddit_eli5,"Imagine a card game where you're a wizard, and..."
9,What are prions and are they a big deal ? My A...,"['Like viruses , they are ( groups of ) molecu...",['Prions are tiny particles that can cause ser...,NaN,reddit_eli5,"Imagine you have LEGO bricks. Normally, they ..."

In [3]:
import pandas as pd

# assuming your dataframe is df

df_long = final_df.melt(
    id_vars=["question", "index", "source"], 
    value_vars=["human_answers", "chatgpt_answers", "answer_gemini"],
    var_name="writer",   # this will now directly hold the column name
    value_name="answer"
)

# remove rows with missing answers
df_long = df_long.dropna(subset=["answer"])

df_long.head()

,question,index,source,writer,answer
0,"Why is every book I hear about a "" NY Times # ...",NaN,reddit_eli5,human_answers,"['Basically there are many categories of "" Bes..."
1,"If salt is so bad for cars , why do we use it ...",NaN,reddit_eli5,human_answers,['salt is good for not dying in car crashes an...
2,Why do we still have SD TV channels when HD lo...,NaN,reddit_eli5,human_answers,"[""The way it works is that old TV stations got..."
3,Why has nobody assassinated Kim Jong - un He i...,NaN,reddit_eli5,human_answers,"[""You ca n't just go around assassinating the ..."
4,How was airplane technology able to advance so...,NaN,reddit_eli5,human_answers,['Wanting to kill the shit out of Germans driv...

In [4]:
# Shuffle all rows randomly
df_long = df_long.sample(frac=1, random_state=42).reset_index(drop=True)

In [5]:
df_long.drop(columns=['index'], inplace=True)

In [6]:
# reorder to [writer, question, answer, source, index]
df_long = df_long[["source", "question", "answer", "writer"]]

In [7]:
df_long.to_csv('final_results_long_format.csv', index=False)